export const theme = {
  colors: {
    primary: '#FF6B35',
    primaryLight: '#FFE5D6',
    primaryDark: '#E55A25',
    secondary: '#004E89',
    secondaryLight: '#E8F1F9',
    secondaryDark: '#003560',
    success: '#10B981',
    successLight: '#D1FAE5',
    warning: '#F59E0B',
    warningLight: '#FEF3C7',
    error: '#EF4444',
    errorLight: '#FEE2E2',
    light: '#F8F9FA',
    dark: '#1F2937',
    white: '#FFFFFF',
    gray: '#6B7280',
    grayLight: '#F3F4F6',
    grayDark: '#374151',
    background: '#F9FAFB',
    border: '#E5E7EB',
  },
  fonts: {
    regular: 'normal',
    bold: 'bold',
    semibold: '600',
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
    xxl: 40,
  },
  borderRadius: {
    small: 6,
    medium: 12,
    large: 16,
    xl: 24,
    full: 9999,
  },
  shadows: {
    small: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 3,
    },
    medium: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.15,
      shadowRadius: 8,
      elevation: 6,
    },
    large: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.2,
      shadowRadius: 12,
      elevation: 10,
    },
  },
  typography: {
    h1: { fontSize: 32, fontWeight: '700', lineHeight: 40 },
    h2: { fontSize: 28, fontWeight: '700', lineHeight: 36 },
    h3: { fontSize: 24, fontWeight: '700', lineHeight: 32 },
    h4: { fontSize: 20, fontWeight: '700', lineHeight: 28 },
    body: { fontSize: 16, fontWeight: '400', lineHeight: 24 },
    bodySm: { fontSize: 14, fontWeight: '400', lineHeight: 20 },
    label: { fontSize: 12, fontWeight: '600', lineHeight: 16 },
  },
};
